### ISSUE TITLE
Can not find BR

### ISSUE THREAD

**Issue by samuel2629** [ma7madfawzy/dialogPlus#4]
2020-05-27 14:20:55.960 23187-23187/com.timenoteco.timenote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.timenoteco.timenote, PID: 23187
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dialog/plus/BR;
        at com.dialog.plus.ui.DialogPlusUiModel.setTitle(DialogPlusUiModel.java:153)
        at com.dialog.plus.ui.DialogPlusBuilder.set(DialogPlusBuilder.java:568)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:46)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:42)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:34)
        at com.timenoteco.timenote.view.ProfilModify.onClick(ProfilModify.kt:50)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dialog.plus.BR" on path: DexPathList[[zip file "/data/app/com.timenoteco.timenote-t1nBYC0QnXWT1zFNVis-3w==/base.apk"],nativeLibraryDirectories=[/data/app/com.timenoteco.timenote-t1nBYC0QnXWT1zFNVis-3w==/lib/x86, /data/app/com.timenoteco.timenote-t1nBYC0QnXWT1zFNVis-3w==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.dialog.plus.ui.DialogPlusUiModel.setTitle(DialogPlusUiModel.java:153) 
        at com.dialog.plus.ui.DialogPlusBuilder.set(DialogPlusBuilder.java:568) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:46) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:42) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:34) 
        at com.timenoteco.timenote.view.ProfilModify.onClick(ProfilModify.kt:50) 
        at android.view.View.performClick(View.java:6597) 
        at android.view.View.performClickInternal(View.java:6574) 
        at android.view.View.access$3100(View.java:778) 
        at android.view.View$PerformClick.run(View.java:25885) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by samuel2629** [comment]
I get it, need to install databinding !
