### ISSUE TITLE
It is not working... 

### ISSUE THREAD

**Issue by krish23** [ma7madfawzy/dialogPlus#5]
I am getting this error when I run custom dialog. 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.project, PID: 3264
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dialog/plus/BR;
        at com.dialog.plus.ui.DialogPlusUiModel.setTitle(DialogPlusUiModel.java:153)
        at com.dialog.plus.ui.DialogPlusBuilder.set(DialogPlusBuilder.java:568)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:46)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:42)
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:34)
        at com.sample.project.Winner.loadWinnerPopup(Winner.java:34)
        at com.sample.project.Winner.onCreate(Winner.java:27)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dialog.plus.BR" on path: DexPathList[[zip file "/data/app/ com.sample.project-1/base.apk"],nativeLibraryDirectories=[/data/app/ com.sample.project-1/lib/x86_64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.dialog.plus.ui.DialogPlusUiModel.setTitle(DialogPlusUiModel.java:153) 
        at com.dialog.plus.ui.DialogPlusBuilder.set(DialogPlusBuilder.java:568) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:46) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:42) 
        at com.dialog.plus.ui.DialogPlusBuilder.<init>(DialogPlusBuilder.java:34) 
        at  com.sample.project.Winner.loadWinnerPopup(Winner.java:34) 
        at  com.sample.project.Winner.onCreate(Winner.java:27) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: com.dialog.plus.BR
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 21 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by krish23** [comment]
I tried this code, still getting same message. WTH!!!! I think your code is not working

```
  private void loadPopup()
    {
        new DialogPlusBuilder("Message Dialog", "message dialog_plus sample\n Welcome Back")
                //@ColorRes int positiveBackground, @ColorRes int negativeColorRes, @ColorRes int headerBgColor
                .setTexts("alright").blurBackground()
                .setBackgrounds(R.color.colorPrimary, R.color.colorAccent)
                .buildMessageDialog(new DialogListener() {//implement functions
                })
                .show(this.getSupportFragmentManager(), "Message Dialog");
    }

    private class DialogListener extends DialogPlus.DialogActionListener {
        @Override
        public void onPositive(DialogPlus dialogPlus) {
            Toast.makeText(Winner.this, "onPositive", Toast.LENGTH_SHORT).show();
            dialogPlus.dismiss(true);
        }

        @Override
        public void onNegative(DialogPlus dialogPlus) {
            super.onNegative(dialogPlus);
            Toast.makeText(Winner.this, "onNegative", Toast.LENGTH_SHORT).show();
        }
    }
```

**Comment by samuel2629** [comment]
I though too at first but you need to install databinding !
